/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interface";
export { ERC1271__factory } from "./ERC1271__factory";
export { ERC165__factory } from "./ERC165__factory";
