/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccountPermissions } from "./IAccountPermissions";
export type { IContractMetadata } from "./IContractMetadata";
export type { IMulticall } from "./IMulticall";
export type { IPermissions } from "./IPermissions";
export type { IPermissionsEnumerable } from "./IPermissionsEnumerable";
