/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interface";
export * as upgradeable from "./upgradeable";
export { Multicall__factory } from "./Multicall__factory";
