/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interface";
export type { interfaces };
import type * as upgradeable from "./upgradeable";
export type { upgradeable };
export type { Multicall } from "./Multicall";
