/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PermissionsStorage,
  PermissionsStorageInterface,
} from "../../../../extension/upgradeable/Permissions.sol/PermissionsStorage";

const _abi = [
  {
    inputs: [],
    name: "PERMISSIONS_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60df610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80630998ed3b146038575b600080fd5b603e6052565b604051604991906090565b60405180910390f35b7f0a7b0f5c59907924802379ebe98cdc23e2ee7820f63d30126e10b3752010e50060001b81565b6000819050919050565b608a816079565b82525050565b600060208201905060a360008301846083565b9291505056fea264697066735822122062222cbab22ec793ab65f0a5aa5df023888bfba6db1fb9182150aa377188522664736f6c634300080c0033";

type PermissionsStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PermissionsStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PermissionsStorage__factory extends ContractFactory {
  constructor(...args: PermissionsStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<PermissionsStorage> {
    return super.deploy(overrides || {}) as Promise<PermissionsStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PermissionsStorage {
    return super.attach(address) as PermissionsStorage;
  }
  override connect(signer: Signer): PermissionsStorage__factory {
    return super.connect(signer) as PermissionsStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PermissionsStorageInterface {
    return new utils.Interface(_abi) as PermissionsStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PermissionsStorage {
    return new Contract(address, _abi, signerOrProvider) as PermissionsStorage;
  }
}
