/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ContractMetadataStorage,
  ContractMetadataStorageInterface,
} from "../../../../extension/upgradeable/ContractMetadata.sol/ContractMetadataStorage";

const _abi = [
  {
    inputs: [],
    name: "CONTRACT_METADATA_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60df610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80637e837fbf146038575b600080fd5b603e6052565b604051604991906090565b60405180910390f35b7f4bc804ba64359c0e35e5ed5d90ee596ecaa49a3a930ddcb1470ea0dd625da90060001b81565b6000819050919050565b608a816079565b82525050565b600060208201905060a360008301846083565b9291505056fea2646970667358221220f8eb0de83ead73a6228e8d3310ed6a050e0a26fe12f70949085bd70996eaff7b64736f6c634300080c0033";

type ContractMetadataStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ContractMetadataStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ContractMetadataStorage__factory extends ContractFactory {
  constructor(...args: ContractMetadataStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractMetadataStorage> {
    return super.deploy(overrides || {}) as Promise<ContractMetadataStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ContractMetadataStorage {
    return super.attach(address) as ContractMetadataStorage;
  }
  override connect(signer: Signer): ContractMetadataStorage__factory {
    return super.connect(signer) as ContractMetadataStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ContractMetadataStorageInterface {
    return new utils.Interface(_abi) as ContractMetadataStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContractMetadataStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ContractMetadataStorage;
  }
}
