/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AccountPermissionsStorage,
  AccountPermissionsStorageInterface,
} from "../../../../extension/upgradeable/AccountPermissions.sol/AccountPermissionsStorage";

const _abi = [
  {
    inputs: [],
    name: "ACCOUNT_PERMISSIONS_STORAGE_POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60df610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806376a00512146038575b600080fd5b603e6052565b604051604991906090565b60405180910390f35b7f3181e78fc1b109bc611fd2406150bf06e33faa75f71cba12c3e1fd670f2def0060001b81565b6000819050919050565b608a816079565b82525050565b600060208201905060a360008301846083565b9291505056fea2646970667358221220bb24980506a5a7b28ce8f83cff5f20fe8ec163a8296e0c2d50c9aa87a8511d6964736f6c634300080c0033";

type AccountPermissionsStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AccountPermissionsStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AccountPermissionsStorage__factory extends ContractFactory {
  constructor(...args: AccountPermissionsStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<AccountPermissionsStorage> {
    return super.deploy(overrides || {}) as Promise<AccountPermissionsStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AccountPermissionsStorage {
    return super.attach(address) as AccountPermissionsStorage;
  }
  override connect(signer: Signer): AccountPermissionsStorage__factory {
    return super.connect(signer) as AccountPermissionsStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AccountPermissionsStorageInterface {
    return new utils.Interface(_abi) as AccountPermissionsStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AccountPermissionsStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AccountPermissionsStorage;
  }
}
