/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interface";
export type { interfaces };
export type { ERC1271 } from "./ERC1271";
export type { ERC165 } from "./ERC165";
